# site settings
title: codemuch
email: ex0dus@codemuch.tech
description: personal site
baseurl: ""
url: https://codemuch.tech
author: alan

tiles-source: pages
tiles-count: 6

github_url: ex0dus-0x
linkedin_url: https://www.linkedin.com/in/alan-cao-7b9bb6bb
twitter_url: https://twitter.com/AlanCao5

# build settings
markdown: kramdown

sass:
  style: compressed
