# Site Info
title:              "Alan Cao | Passionate Systems Engineer and Researcher"
description:        "Personal Portfolio and Blog"
author_name:        "Alan Cao"
logo_url:           https://avatars2.githubusercontent.com/u/17283637?v=4

# Site Settings
url:                https://codemuch.tech
baseurl:
permalink:          /:title # Post permalink
timezone:           America/New_York
mathjax:            true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:            GFM
    parse_block_html: true

sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
